[package]
name = "globwalk"
version = "0.1.0"
description = "Glob-matched recursive file system walking."
authors = ["Gilad Naaman <gilad.naaman@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/gilnaa/globwalk"
categories = ["filesystem"]
keywords = ["regex", "glob", "pattern", "walk", "iterator"]

[dependencies]
walkdir = "2"
globset = "0.2"

[dev-dependencies]
tempdir = "0.3"
